apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: ninja-board-pipeline
spec:
  params:
    - default: 'https://github.com/rafamqrs/ninja-board'
      name: git
      type: string
    - default: modernization
      name: branch
      type: string
    - default: workspace/source/ninja-board-be-helm/
      name: workspace_dir
      type: string
  tasks:
    - name: git-clone
      params:
        - name: url
          value: $(params.git)
        - name: revision
          value: $(params.branch)
        - name: submodules
          value: 'true'
        - name: depth
          value: '1'
        - name: sslVerify
          value: 'true'
        - name: crtFileName
          value: ca-bundle.crt
        - name: deleteExisting
          value: 'true'
        - name: verbose
          value: 'true'
        - name: gitInitImage
          value: >-
            registry.redhat.io/openshift-pipelines/pipelines-git-init-rhel8@sha256:a538c423e7a11aae6ae582a411fdb090936458075f99af4ce5add038bb6983e8
        - name: userHome
          value: /tekton/home
      taskRef:
        kind: ClusterTask
        name: git-clone-1-8-0
      workspaces:
        - name: output
          workspace: pipeline-pvc
    - name: package
      params:
        - name: MAVEN_IMAGE
          value: >-
            image-registry.openshift-image-registry.svc:5000/openshift/java:latest
        - name: GOALS
          value:
            - package
        - name: PROXY_PROTOCOL
          value: http
        - name: CONTEXT_DIR
          value: ninja-board-quarkus/
      runAfter:
        - ls-files
      taskRef:
        kind: ClusterTask
        name: maven-1-8-0
      workspaces:
        - name: maven-settings
          workspace: pipeline-pvc
        - name: source
          workspace: pipeline-pvc
    - name: ls-files
      runAfter:
        - git-clone
      taskRef:
        kind: Task
        name: ls-files
    - name: buildah-custom
      params:
        - name: IMAGE
          value: quay.io/rhn_support_rmarques/ninja-board
        - name: BUILDER_IMAGE
          value: registry.redhat.io/rhel8/buildah
        - name: STORAGE_DRIVER
          value: vfs
        - name: DOCKERFILE
          value: ninja-board-quarkus/src/main/docker/Dockerfile.jvm
        - name: CONTEXT
          value: ninja-board-quarkus/
        - name: TLSVERIFY
          value: 'true'
        - name: FORMAT
          value: oci
        - name: SKIP_PUSH
          value: 'false'
      runAfter:
        - package
      taskRef:
        kind: ClusterTask
        name: buildah-custom
      workspaces:
        - name: source
          workspace: pipeline-pvc
    - name: helm-install
      params:
        - name: helm_repo
          value: teste
        - name: chart_name
          value: $(params.workspace_dir)
        - name: release_version
          value: v1.0.0
        - name: release_name
          value: ninja-board-be
        - name: overwrite_values
          value: $(params.workspace_dir)values.yaml
        - name: helm_image
          value: >-
            docker.io/lachlanevenson/k8s-helm@sha256:5c792f29950b388de24e7448d378881f68b3df73a7b30769a6aa861061fd08ae
      runAfter:
        - buildah-custom
      taskRef:
        kind: Task
        name: helm-install
      workspaces:
        - name: source
          workspace: pipeline-pvc
  workspaces:
    - name: pipeline-pvc
