quarkus.log.level=INFO
quarkus.log.category."com.redhat.services.portfolio".level=INFO
quarkus.log.category."com.redhat.services.portfolio.auth".level=INFO
quarkus.log.category."com.redhat.services.portfolio.controllers".level=INFO
quarkus.log.category."com.redhat.services.portfolio.auth.OAuth".level=INFO
quarkus.log.category."com.redhat.services.portfolio.auth.AuthFilter2".level=INFO

# https://quarkus.io/guides/logging
#quarkus.log.console.format=%d{yyyy-MM-dd HH:mm:ss} %-5p [%c] (%t) %s%e%n
quarkus.log.console.format=%d{yy-MM-dd HH:mm:ss} %-5p [%c{2.}] (%t{id}) %s%e%n

# logging in Splunk - index="rh_paas" kubernetes.namespace_name="customer-success-portfolio-hub--prod" message = "*AuthFilter2*"
#Preparation for Splunk logging
#quarkus.log.file.enable=true
#quarkus.log.file.format=%d{yyyy-MM-dd HH:mm:ss,SSS} %-5p [%c{3.}] (%t) %s%e%n
#quarkus.log.category."com.redhat.services.portfolio.auth.AuthFilter2".handlers=SPLUNK
#quarkus.log.handler.file.SPLUNK.enable=true
#quarkus.log.handler.file.SPLUNK.path=logs/splunk.log

#quarkus.swagger-ui.always-include=false
#quarkus.swagger-ui.enable=false
#quarkus.swagger-ui.path=/api

quarkus.naming.enable-jndi=true
#quarkus.http.cors=true
#quarkus.http.port=8080
#quarkus.http.cors.origins=*
#quarkus.http.cors.headers=accept, authorization, content-type, x-requested-with
#quarkus.http.cors.methods=GET,POST,PUT,DELETE,OPTIONS

quarkus.thread-pool.max-threads=50
quarkus.thread-pool.queue-size=100

cmdb.id=GVBK-001
storage.root=${STORAGE_ROOT}

authenticated.paths={"/auth((?!callback|userInfo).)*":["ADMIN"],"/admin.*":["ADMIN"],"/config.*":["ADMIN"]}
authenticated.user.roles.default={"mallen@redhat.com":["ADMIN"],"ablock@redhat.com":["ADMIN"]}

notifications.enabled=${NOTIFICATIONS_ENABLED}
notifications.app.name=Communities of Practice - Giveback
notifications.sslcertstrustall=true
notifications.googlechat.template={'text':'TASK_NAME is DOWN! returned RESPONSE_CODE! - <https://watcher.apps.int.spoke.prod.us-east-1.aws.paas.redhat.com/tasks|Watcher>'}
notifications.slack.template={\"app\":\"TASK_NAME\", \"text\":\"MESSAGE_TEXT\", \"status\":\"RESPONSE_CODE\", \"icon_emoji\":\":ghost:\"}
notifications=     [{"type":"slack","events":"onHttpFailure,onError,onWarning","channel":"https://hooks.slack.com/triggers/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","enabled":true}]
notifications.test=[{"type":"slack","events":"onHttpFailure,onError,onWarning","channel":"https://hooks.slack.com/triggers/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","enabled":true}]
notifications.live=[{"type":"slack","events":"onHttpFailure,onError,onWarning","channel":"https://hooks.slack.com/triggers/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","enabled":true}]

google.oauth.enabled=true
google.oauth.clientId=1080390017142-pbm4rjmtn88hi01bulf4svafaumqj1q7.apps.googleusercontent.com
google.oauth.secret=${GIVEBACK_GOOGLE_OAUTH_SECRET}
google.oauth.signIn=/signin
google.oauth.signIn.iframe=/signin.html
#google.oauth.signIn.iframe=/signin.html?returnUrl=/search
#google.oauth.redirectUri=http://localhost:8083/auth/callback
# DO NOT COMMIT THE http:// value here, it will cause a failure on the server
#google.oauth.redirectUri=http://%s/auth/callback


