@Library('cop-library') _

openshift.withCluster() {
  env.localToken = readFile('/var/run/secrets/kubernetes.io/serviceaccount/token').trim()
  env.NAMESPACE = openshift.project()
}

pipeline {
  agent {
    label 'nodejs'
  }

  stages {
    stage ('Fetch Source Code') {
      steps {
          git url: "${SOURCE_REPOSITORY_URL}", branch: "${SOURCE_REPOSITORY_REF}"
      }
    }

    stage('Build Application'){
      steps {
        sh """
          cd react/ninja-react
          npm install
          npm run build
        """
      }
    }

    stage('Build Image'){
      steps {
        script {
          openshift.withCluster() {
            openshift.withProject("${DEV_NAMESPACE}") {
              openshift.selector("bc", "${APPLICATION_NAME}").startBuild("--from-dir=react/ninja-react/build").logs("-f")
            }
          }
        }

      }
    }

    stage ('Verify Deployment to Dev') {
      steps {
        rollout([projectName: "${DEV_NAMESPACE}", resourceKindAndName: "dc/${APPLICATION_NAME}", latest: false])
      }
    }
  }
}
