/**
 * Giveback Ninja
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.GivebackNinja);
  }
}(this, function(expect, GivebackNinja) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new GivebackNinja.User();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('User', function() {
    it('should create an instance of User', function() {
      // uncomment below and update the code to test User
      //var instane = new GivebackNinja.User();
      //expect(instance).to.be.a(GivebackNinja.User);
    });

    it('should have the property displayName (base name: "displayName")', function() {
      // uncomment below and update the code to test the property displayName
      //var instane = new GivebackNinja.User();
      //expect(instance).to.be();
    });

    it('should have the property username (base name: "username")', function() {
      // uncomment below and update the code to test the property username
      //var instane = new GivebackNinja.User();
      //expect(instance).to.be();
    });

    it('should have the property githubUsername (base name: "githubUsername")', function() {
      // uncomment below and update the code to test the property githubUsername
      //var instane = new GivebackNinja.User();
      //expect(instance).to.be();
    });

    it('should have the property trelloUsername (base name: "trelloUsername")', function() {
      // uncomment below and update the code to test the property trelloUsername
      //var instane = new GivebackNinja.User();
      //expect(instance).to.be();
    });

    it('should have the property email (base name: "email")', function() {
      // uncomment below and update the code to test the property email
      //var instane = new GivebackNinja.User();
      //expect(instance).to.be();
    });

  });

}));
